title: Juan Manuel Carrillo de Gea # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <strong>Associate Professor</strong>
  <br><br>
  Room 2.07<br>
  <a href="http://www.um.es/web/dis/" target="_top">Department of Informatics and Systems</a><br>
  <a href="http://www.um.es/informatica/index.php" target="_top">Faculty of Computer Science</a><br>
  <a href="http://www.um.es/" target="_top">University of Murcia</a><br>
  Campus Universitario de Espinardo<br>
  30100 Murcia (Spain)
  <br><br>
  Phone: +34 868 88 46 06<br>
  Mobile: +34 625 91 85 58<br>
  Fax: +34 868 88 41 51<br>
  Email: <a href='&#109;&#97;ilt&#111;&#58;jmcd&#103;&#49;&#64;%75m%2&#69;e&#115;'>&#106;m&#99;dg&#49;&#64;&#117;m&#46;es</a><br>
  Skype: <a href="skype:jmcarrillodegea?chat" target="_top">jmcarrillodegea</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
